### ISSUE TITLE
Server Error (500) when trying to open apps in wharf dashboard

### ISSUE THREAD

**Issue by gschurck** [palfrey/wharf#125]
When trying to open an app from the list in wharf home dashboard, I get a Server Error (500).
I followed installation instructions, but I couldn't get it to work
Wharf is installed as a Dokku app in the same server.

`dokku logs wharf` : 

```
2022-01-23T21:03:03.170950607Z app[web.1]: Operations to perform:
2022-01-23T21:03:03.170955466Z app[web.1]:   Apply all migrations: admin, apps, auth, contenttypes, django_celery_results, sessions
2022-01-23T21:03:03.170957891Z app[web.1]: Running migrations:
2022-01-23T21:03:03.170960155Z app[web.1]:   No migrations to apply.
2022-01-23T21:03:03.332132529Z app[web.1]: + python manage.py runserver 0.0.0.0:5000
2022-01-23T21:03:04.224941156Z app[web.1]: Watching for file changes with StatReloader
2022-01-23T21:03:04.539642516Z app[web.1]: System check identified some issues:
2022-01-23T21:03:04.539662875Z app[web.1]: 
2022-01-23T21:03:04.539665861Z app[web.1]: WARNINGS:
2022-01-23T21:03:04.539668245Z app[web.1]: ?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.
2022-01-23T21:03:04.539670780Z app[web.1]: apps.TaskLog.success: (fields.W903) NullBooleanField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
2022-01-23T21:03:04.539673235Z app[web.1]:      HINT: Use BooleanField(null=True) instead.
2022-01-23T21:03:04.539675960Z app[web.1]: 
2022-01-23T21:03:04.539678084Z app[web.1]: System check identified 2 issues (0 silenced).
2022-01-23T21:11:18.698853567Z app[web.1]: "GET / HTTP/1.1" 200 3564
2022-01-23T21:11:24.649689034Z app[web.1]: /usr/local/lib/python3.8/site-packages/django/db/models/fields/__init__.py:1367: RuntimeWarning: DateTimeField TaskLog.when received a naive datetime (2022-01-23 21:11:24.637743) while time zone support is active.
2022-01-23T21:11:24.649711498Z app[web.1]:   warnings.warn("DateTimeField %s received a naive datetime (%s)"
2022-01-23T21:11:24.649716036Z app[web.1]: "POST / HTTP/1.1" 302 0
2022-01-23T21:11:24.725167779Z app[web.1]: "GET /apps/test/wait/5c13c6c4-2ee0-4a6c-b381-1afed86d5f93/check_app HTTP/1.1" 200 1560
2022-01-23T21:11:26.817940178Z app[web.1]: "GET /apps/test/wait/5c13c6c4-2ee0-4a6c-b381-1afed86d5f93/check_app HTTP/1.1" 302 0
2022-01-23T21:11:26.860993232Z app[web.1]: Internal Server Error: /apps/test/check_app/5c13c6c4-2ee0-4a6c-b381-1afed86d5f93
2022-01-23T21:11:26.861059258Z app[web.1]: Traceback (most recent call last):
2022-01-23T21:11:26.861065510Z app[web.1]:   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2022-01-23T21:11:26.861070840Z app[web.1]:     response = get_response(request)
2022-01-23T21:11:26.861075409Z app[web.1]:   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2022-01-23T21:11:26.861109855Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-01-23T21:11:26.861134542Z app[web.1]:   File "/app/apps/views.py", line 380, in check_app
2022-01-23T21:11:26.861139181Z app[web.1]:     raise Exception(data)
2022-01-23T21:11:26.861143228Z app[web.1]: Exception: -----> Creating test...
2022-01-23T21:11:26.861147867Z app[web.1]: 
2022-01-23T21:11:26.861460696Z app[web.1]: "GET /apps/test/check_app/5c13c6c4-2ee0-4a6c-b381-1afed86d5f93 HTTP/1.1" 500 145
2022-01-23T21:11:30.891007353Z app[web.1]: "GET / HTTP/1.1" 200 3564
2022-01-23T21:11:31.867745322Z app[web.1]: "GET / HTTP/1.1" 200 3564
2022-01-23T21:11:32.564761656Z app[web.1]: "GET / HTTP/1.1" 200 3564
2022-01-23T21:11:34.799151001Z app[web.1]: Internal Server Error: /apps/django-ttm
2022-01-23T21:11:34.799190677Z app[web.1]: Traceback (most recent call last):
2022-01-23T21:11:34.799195105Z app[web.1]:   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2022-01-23T21:11:34.799198241Z app[web.1]:     response = get_response(request)
2022-01-23T21:11:34.799200586Z app[web.1]:   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2022-01-23T21:11:34.799203100Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-01-23T21:11:34.799205745Z app[web.1]:   File "/app/apps/views.py", line 306, in app_info
2022-01-23T21:11:34.799208090Z app[web.1]:     'postgres': postgres_list(app_name),
2022-01-23T21:11:34.799210394Z app[web.1]:   File "/app/apps/views.py", line 221, in postgres_list
2022-01-23T21:11:34.799212739Z app[web.1]:     return db_list(app_name, data)
2022-01-23T21:11:34.799214953Z app[web.1]:   File "/app/apps/views.py", line 216, in db_list
2022-01-23T21:11:34.799217227Z app[web.1]:     return generic_list(app_name, data, "NAME", ["NAME", "VERSION", "STATUS", "EXPOSED PORTS", "LINKS"])
2022-01-23T21:11:34.799220144Z app[web.1]:   File "/app/apps/views.py", line 192, in generic_list
2022-01-23T21:11:34.799222558Z app[web.1]:     raise Exception("Can't find '%s' in '%s'" % (f, lines[0].strip()))
2022-01-23T21:11:34.799224953Z app[web.1]: Exception: Can't find 'NAME' in '=====> Postgres services'
2022-01-23T21:11:34.799750577Z app[web.1]: "GET /apps/django-ttm HTTP/1.1" 500 145
2022-01-23T21:12:22.103659241Z app[web.1]: Internal Server Error: /apps/django-ttm
2022-01-23T21:12:22.103698416Z app[web.1]: Traceback (most recent call last):
2022-01-23T21:12:22.103701873Z app[web.1]:   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
2022-01-23T21:12:22.103704778Z app[web.1]:     response = get_response(request)
2022-01-23T21:12:22.103707383Z app[web.1]:   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
2022-01-23T21:12:22.103710278Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2022-01-23T21:12:22.103712943Z app[web.1]:   File "/app/apps/views.py", line 306, in app_info
2022-01-23T21:12:22.103728995Z app[web.1]:     'postgres': postgres_list(app_name),
2022-01-23T21:12:22.103731379Z app[web.1]:   File "/app/apps/views.py", line 221, in postgres_list
2022-01-23T21:12:22.103733754Z app[web.1]:     return db_list(app_name, data)
2022-01-23T21:12:22.103735968Z app[web.1]:   File "/app/apps/views.py", line 216, in db_list
2022-01-23T21:12:22.103738282Z app[web.1]:     return generic_list(app_name, data, "NAME", ["NAME", "VERSION", "STATUS", "EXPOSED PORTS", "LINKS"])
2022-01-23T21:12:22.103741218Z app[web.1]:   File "/app/apps/views.py", line 192, in generic_list
2022-01-23T21:12:22.103743632Z app[web.1]:     raise Exception("Can't find '%s' in '%s'" % (f, lines[0].strip()))
2022-01-23T21:12:22.103746057Z app[web.1]: Exception: Can't find 'NAME' in '+ export DOKKU_HOST_ROOT=/home/dokku'

```

**Comment by gschurck** [comment]
The last one, 1.19.2

**Comment by palfrey** [comment]
We only support up to 1.9.5, as per the README

**Comment by gschurck** [comment]
Is it possible to contribute to update that ?

**Comment by palfrey** [comment]
> Is it possible to contribute to update that ?

Yes. See comments starting at https://github.com/palfrey/wharf/issues/75#issuecomment-741077026
