### ISSUE TITLE
User Wharf does not have permissions to run apps:list.

### ISSUE THREAD

**Issue by snow-sr** [palfrey/wharf#134]
Hey there!
So, I'm trying to use wharf for a while now, I've tried to re-install it a lot of times, but it's not working as expected.
After loggin-in, I receive this error:
```Server Error (500)``` 
And my dokku logs says:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/app/apps/views.py", line 115, in index
    apps = app_list()
  File "/app/apps/views.py", line 110, in app_list
    raise Exception(data)
Exception: !     User wharf does not have permissions to run apps:list
 !     Access denied
"GET / HTTP/1.1" 500 145
"GET /favicon.ico HTTP/1.1" 302 0
Not Found: /static/favicon.ico
"GET /static/favicon.ico HTTP/1.1" 404 179
```

**Comment by palfrey** [comment]
Assuming this is solved given lack of response
