### ISSUE TITLE
Internal Server Error when trying to open app details

### ISSUE THREAD

**Issue by IrregularShed** [palfrey/wharf#39]
Following on from #33, I've now got Wharf installed and showing the apps running on Dokku. However, clicking on any one of those apps returns a very plain 500 error:
![image](https://user-images.githubusercontent.com/190127/52291874-4d803c80-296b-11e9-94dc-e24de3ff18d8.png)
I'm beginning to get a handle on the way things work, so I got the logs up in Dokku, which has this error showing:
```
2019-02-05T17:20:42.460389257Z app[web.1]: Internal Server Error: /apps/wharf
2019-02-05T17:20:42.460444396Z app[web.1]: Traceback (most recent call last):
2019-02-05T17:20:42.460468240Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
2019-02-05T17:20:42.460494711Z app[web.1]:     response = get_response(request)
2019-02-05T17:20:42.460517079Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
2019-02-05T17:20:42.460573670Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2019-02-05T17:20:42.460596134Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
2019-02-05T17:20:42.460618837Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2019-02-05T17:20:42.460640077Z app[web.1]:   File "/app/apps/views.py", line 285, in app_info
2019-02-05T17:20:42.460660980Z app[web.1]:     app = models.App.objects.get(name=app_name)
2019-02-05T17:20:42.460681740Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
2019-02-05T17:20:42.460703148Z app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
2019-02-05T17:20:42.460723991Z app[web.1]:   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
2019-02-05T17:20:42.460745555Z app[web.1]:     self.model._meta.object_name
2019-02-05T17:20:42.460766027Z app[web.1]: apps.models.App.DoesNotExist: App matching query does not exist.
2019-02-05T17:20:42.463751118Z app[web.1]: "GET /apps/wharf HTTP/1.1" 500 27
```

This is true for all the apps I have under Dokku.

Trying to add a new `config:set` key/value appears initially to work, but the page refreshes and I get that 500 error again. It also happens when trying to create a new app - a brief flash that suggests that it might be working, followed by a 500.

I've followed the whole setup procedure (several times now, as I've been trying things out), so Redis, SSH key storage, etc are all taken care of. Is there anything more I can try that will help clear this?

**Comment by palfrey** [comment]
@IrregularShed Any better now?

**Comment by IrregularShed** [comment]
Brilliant! It's working for me - I'll close this now.

**Comment by Fenn-CS** [comment]
Hello there, this issue still seems to persists for both existing and newly created apps via wharf.

```
root@sevengroup-server-dokku:~# dokku logs wharf
2020-09-29T19:25:42.763305598Z app[web.1]:   Applying auth.0007_alter_validators_add_error_messages... OK
2020-09-29T19:25:42.763308786Z app[web.1]:   Applying auth.0008_alter_user_username_max_length... OK
2020-09-29T19:25:42.763312061Z app[web.1]:   Applying auth.0009_alter_user_last_name_max_length... OK
2020-09-29T19:25:42.763316716Z app[web.1]:   Applying auth.0010_alter_group_name_max_length... OK
2020-09-29T19:25:42.763321158Z app[web.1]:   Applying auth.0011_update_proxy_permissions... OK
2020-09-29T19:25:42.763325799Z app[web.1]:   Applying django_celery_results.0001_initial... OK
2020-09-29T19:25:42.763330701Z app[web.1]:   Applying sessions.0001_initial... OK
2020-09-29T19:25:42.982838402Z app[web.1]: + python manage.py runserver 0.0.0.0:5000
2020-09-29T19:25:44.972661714Z app[web.1]: Watching for file changes with StatReloader
2020-09-29T19:26:21.959296115Z app[web.1]: "GET /article/legal-y-politica/politica/261417-el-indulto-gran-reconciliador-sera/ HTTP/1.1" 302 0
2020-09-29T19:26:22.110764142Z app[web.1]: "GET /accounts/login/?next=/article/legal-y-politica/politica/261417-el-indulto-gran-reconciliador-sera/ HTTP/1.1" 200 2088
2020-09-29T19:26:43.494270985Z app[web.1]: "GET / HTTP/1.1" 302 0
2020-09-29T19:26:43.961074649Z app[web.1]: "GET /accounts/login/ HTTP/1.1" 200 2011
2020-09-29T19:26:50.348228813Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:26:51.105187170Z app[web.1]: "GET /static/favicon.ico HTTP/1.1" 302 0
2020-09-29T19:26:51.600042918Z app[web.1]: "GET /accounts/login/?next=/static/favicon.ico HTTP/1.1" 200 2030
2020-09-29T19:26:53.269365757Z app[web.1]: "GET /proxy.php HTTP/1.1" 302 0
2020-09-29T19:31:48.436809457Z app[web.1]: "POST /accounts/login/ HTTP/1.1" 302 0
2020-09-29T19:31:50.455768389Z app[web.1]: "GET / HTTP/1.1" 200 2120
2020-09-29T19:31:51.458546269Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:31:52.437837006Z app[web.1]: Not Found: /static/favicon.ico
2020-09-29T19:31:52.448392050Z app[web.1]: "GET /static/favicon.ico HTTP/1.1" 404 179
2020-09-29T19:31:58.996509511Z app[web.1]: "GET /robots.txt HTTP/1.1" 302 0
2020-09-29T19:31:59.037531187Z app[web.1]: "GET /accounts/login/?next=/robots.txt HTTP/1.1" 200 2022
2020-09-29T19:33:32.672414773Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:36:26.609519814Z app[web.1]: "GET / HTTP/1.1" 302 0
2020-09-29T19:41:05.850679292Z app[web.1]: "GET / HTTP/1.1" 200 3688
2020-09-29T19:41:08.113824021Z app[web.1]: Not Found: /static/favicon.ico
2020-09-29T19:41:08.114834622Z app[web.1]: "GET /static/favicon.ico HTTP/1.1" 404 179
2020-09-29T19:41:35.838030153Z app[web.1]: "POST /refresh HTTP/1.1" 302 0
2020-09-29T19:41:44.791693210Z app[web.1]: "GET / HTTP/1.1" 200 3688
2020-09-29T19:42:05.477643725Z app[web.1]: Internal Server Error: /apps/wharf
2020-09-29T19:42:05.477684002Z app[web.1]: Traceback (most recent call last):
2020-09-29T19:42:05.477689001Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-09-29T19:42:05.477693435Z app[web.1]:     response = get_response(request)
2020-09-29T19:42:05.477697546Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-09-29T19:42:05.477701515Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-09-29T19:42:05.477705389Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-09-29T19:42:05.477710708Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-09-29T19:42:05.477714465Z app[web.1]:   File "/app/apps/views.py", line 304, in app_info
2020-09-29T19:42:05.477718204Z app[web.1]:     'postgres': postgres_list(app_name),
2020-09-29T19:42:05.477721857Z app[web.1]:   File "/app/apps/views.py", line 221, in postgres_list
2020-09-29T19:42:05.477740676Z app[web.1]:     return db_list(app_name, data)
2020-09-29T19:42:05.477744616Z app[web.1]:   File "/app/apps/views.py", line 216, in db_list
2020-09-29T19:42:05.477748301Z app[web.1]:     return generic_list(app_name, data, "NAME", ["NAME", "VERSION", "STATUS", "EXPOSED PORTS", "LINKS"])
2020-09-29T19:42:05.477752876Z app[web.1]:   File "/app/apps/views.py", line 192, in generic_list
2020-09-29T19:42:05.477756570Z app[web.1]:     raise Exception("Can't find '%s' in '%s'" % (f, lines[0].strip()))
2020-09-29T19:42:05.477769648Z app[web.1]: Exception: Can't find 'NAME' in '=====> Postgres services'
2020-09-29T19:42:05.479222217Z app[web.1]: "GET /apps/wharf HTTP/1.1" 500 145
2020-09-29T19:42:07.804482193Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:42:08.661094732Z app[web.1]: Not Found: /static/favicon.ico
2020-09-29T19:42:08.662054951Z app[web.1]: "GET /static/favicon.ico HTTP/1.1" 404 179
2020-09-29T19:42:13.216129112Z app[web.1]: Internal Server Error: /apps/wharf
2020-09-29T19:42:13.216173096Z app[web.1]: Traceback (most recent call last):
2020-09-29T19:42:13.216179374Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-09-29T19:42:13.216184296Z app[web.1]:     response = get_response(request)
2020-09-29T19:42:13.216188816Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-09-29T19:42:13.216193786Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-09-29T19:42:13.216198213Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-09-29T19:42:13.216203034Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-09-29T19:42:13.216207320Z app[web.1]:   File "/app/apps/views.py", line 304, in app_info
2020-09-29T19:42:13.216212095Z app[web.1]:     'postgres': postgres_list(app_name),
2020-09-29T19:42:13.216216325Z app[web.1]:   File "/app/apps/views.py", line 221, in postgres_list
2020-09-29T19:42:13.216220600Z app[web.1]:     return db_list(app_name, data)
2020-09-29T19:42:13.216224764Z app[web.1]:   File "/app/apps/views.py", line 216, in db_list
2020-09-29T19:42:13.216229079Z app[web.1]:     return generic_list(app_name, data, "NAME", ["NAME", "VERSION", "STATUS", "EXPOSED PORTS", "LINKS"])
2020-09-29T19:42:13.216234292Z app[web.1]:   File "/app/apps/views.py", line 192, in generic_list
2020-09-29T19:42:13.216238695Z app[web.1]:     raise Exception("Can't find '%s' in '%s'" % (f, lines[0].strip()))
2020-09-29T19:42:13.216243280Z app[web.1]: Exception: Can't find 'NAME' in '=====> Postgres services'
2020-09-29T19:42:13.217820362Z app[web.1]: "GET /apps/wharf HTTP/1.1" 500 145
2020-09-29T19:42:14.159140894Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:42:15.234403445Z app[web.1]: Not Found: /static/favicon.ico
2020-09-29T19:42:15.239537545Z app[web.1]: "GET /static/favicon.ico HTTP/1.1" 404 179
2020-09-29T19:42:15.512865354Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:42:15.598089691Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:42:16.684148249Z app[web.1]: Not Found: /static/favicon.ico
2020-09-29T19:42:16.685144101Z app[web.1]: "GET /static/favicon.ico HTTP/1.1" 404 179
2020-09-29T19:44:23.905552719Z app[web.1]: Internal Server Error: /apps/wharf
2020-09-29T19:44:23.905602592Z app[web.1]: Traceback (most recent call last):
2020-09-29T19:44:23.905610021Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-09-29T19:44:23.905616413Z app[web.1]:     response = get_response(request)
2020-09-29T19:44:23.905622278Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-09-29T19:44:23.905628951Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-09-29T19:44:23.905656365Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-09-29T19:44:23.905663135Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-09-29T19:44:23.905669042Z app[web.1]:   File "/app/apps/views.py", line 304, in app_info
2020-09-29T19:44:23.905674503Z app[web.1]:     'postgres': postgres_list(app_name),
2020-09-29T19:44:23.905679681Z app[web.1]:   File "/app/apps/views.py", line 221, in postgres_list
2020-09-29T19:44:23.905685307Z app[web.1]:     return db_list(app_name, data)
2020-09-29T19:44:23.905690626Z app[web.1]:   File "/app/apps/views.py", line 216, in db_list
2020-09-29T19:44:23.905696625Z app[web.1]:     return generic_list(app_name, data, "NAME", ["NAME", "VERSION", "STATUS", "EXPOSED PORTS", "LINKS"])
2020-09-29T19:44:23.905703092Z app[web.1]:   File "/app/apps/views.py", line 192, in generic_list
2020-09-29T19:44:23.905708205Z app[web.1]:     raise Exception("Can't find '%s' in '%s'" % (f, lines[0].strip()))
2020-09-29T19:44:23.905713429Z app[web.1]: Exception: Can't find 'NAME' in '=====> Postgres services'
2020-09-29T19:44:23.908342091Z app[web.1]: "GET /apps/wharf HTTP/1.1" 500 145
2020-09-29T19:44:24.832397318Z app[web.1]: "GET /favicon.ico HTTP/1.1" 302 0
2020-09-29T19:44:38.488109320Z app[web.1]: Not Found: /static/favicon.ico
2020-09-29T19:44:38.489313673Z app[web.1]: "GET /static/favicon.ico HTTP/1.1" 404 179
2020-09-29T19:48:51.130418050Z app[web.1]: "POST / HTTP/1.1" 302 0
2020-09-29T19:48:51.289671859Z app[web.1]: "GET /accounts/login/ HTTP/1.1" 200 2011
```

**Comment by palfrey** [comment]
Different bug. You've hit a duplicate of https://github.com/palfrey/wharf/issues/83. Downgrade the Postgres plugin to the ranges listed in the README and it should be fine.

**Comment by Fenn-CS** [comment]
@palfrey thank you, can't find any guidelines on how to install particular versions though. Any pointers?

**Comment by palfrey** [comment]
> @palfrey thank you, can't find any guidelines on how to install particular versions though. Any pointers?

Try the `--committish` arg to the plugin install
