### ISSUE TITLE
Adding new apps fails

### ISSUE THREAD

**Issue by palfrey** [palfrey/wharf#6]
```Traceback (most recent call last):
2018-03-28T09:52:12.851021358Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
2018-03-28T09:52:12.851043374Z app[web.1]:     response = get_response(request)
2018-03-28T09:52:12.851064526Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
2018-03-28T09:52:12.851086292Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2018-03-28T09:52:12.851107676Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
2018-03-28T09:52:12.851129211Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-03-28T09:52:12.851150645Z app[web.1]:   File "/app/apps/views.py", line 71, in wait_for_command
2018-03-28T09:52:12.851171698Z app[web.1]:     app = models.App.objects.get(name=app_name)
2018-03-28T09:52:12.851192641Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
2018-03-28T09:52:12.851214046Z app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
2018-03-28T09:52:12.851235039Z app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
2018-03-28T09:52:12.851256654Z app[web.1]:     self.model._meta.object_name
2018-03-28T09:52:12.852006794Z app[web.1]: apps.models.DoesNotExist: App matching query does not exist.```

**Comment by palfrey** [comment]
https://github.com/heroku-python/bottle-helloworld is probably a reasonable small test app
