### ISSUE TITLE
can't deploy wharf

### ISSUE THREAD

**Issue by seiyria** [palfrey/wharf#80]
I've just fired up a new digitalocean dokku instance (ubuntu 18.04, dokku 0.17.9) and wharf is now failing to deploy with the following error:

```
$ git push dokku
Enumerating objects: 962, done.
Counting objects: 100% (962/962), done.
Delta compression using up to 8 threads
Compressing objects: 100% (415/415), done.
Writing objects: 100% (962/962), 394.20 KiB | 8.57 MiB/s, done.
Total 962 (delta 628), reused 778 (delta 528)
remote: Resolving deltas: 100% (628/628), done.
-----> Cleaning up...
-----> Building wharf from dockerfile...
remote: build context to Docker daemon  433.2kB
Step 1/5 : FROM python:3.6
 ---> c4f7d42f7b89
Step 2/5 : WORKDIR /app
 ---> Using cache
 ---> f979db26d28a
Step 3/5 : COPY requirements.txt /app
 ---> f2a7b174af92
Step 4/5 : RUN pip install -r requirements.txt
 ---> Running in 3819e0af2f8c
Obtaining django-jinja from git+https://github.com/niwinz/django-jinja.git@819a5faddea5341d990ac337b05e7827ac5b4431#egg=django-jinja (from -r requirements.txt (line 7))
  Cloning https://github.com/niwinz/django-jinja.git (to revision 819a5faddea5341d990ac337b05e7827ac5b4431) to ./src/django-jinja
  Running command git clone -q https://github.com/niwinz/django-jinja.git /app/src/django-jinja
  Running command git checkout -q 819a5faddea5341d990ac337b05e7827ac5b4431
Collecting amqp==2.3.2
  Downloading amqp-2.3.2-py2.py3-none-any.whl (48 kB)
Collecting asgiref==3.2.3
  Downloading asgiref-3.2.3-py2.py3-none-any.whl (18 kB)
Collecting asn1crypto==0.24.0
  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)
Collecting bcrypt==3.1.4
  Downloading bcrypt-3.1.4-cp36-cp36m-manylinux1_x86_64.whl (54 kB)
Collecting billiard==3.5.0.3
  Downloading billiard-3.5.0.3-py3-none-any.whl (89 kB)
Collecting celery[redis]==4.1.1
  Downloading celery-4.1.1-py2.py3-none-any.whl (394 kB)
Collecting certifi==2018.4.16
  Downloading certifi-2018.4.16-py2.py3-none-any.whl (150 kB)
Collecting cffi==1.11.5
  Downloading cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl (421 kB)
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting cryptography==2.3
  Downloading cryptography-2.3-cp34-abi3-manylinux1_x86_64.whl (2.1 MB)
Collecting dj-database-url==0.5.0
  Downloading dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Collecting django-celery-results==1.0.1
  Downloading django_celery_results-1.0.1-py2.py3-none-any.whl (12 kB)
Collecting django-jinja-bootstrap-form==4.2.3
  Downloading django_jinja_bootstrap_form-4.2.3-py36-none-any.whl (7.8 kB)
Collecting django-redis==4.11.0
  Downloading django_redis-4.11.0-py3-none-any.whl (18 kB)
Collecting django==3.0.3
  Downloading Django-3.0.3-py3-none-any.whl (7.5 MB)
Collecting gitdb2==2.0.3
  Downloading gitdb2-2.0.3-py2.py3-none-any.whl (63 kB)
Collecting gitpython==2.1.10
  Downloading GitPython-2.1.10-py2.py3-none-any.whl (449 kB)
Collecting humanize==0.5.1
  Downloading humanize-0.5.1.tar.gz (14 kB)
Collecting idna==2.6
  Downloading idna-2.6-py2.py3-none-any.whl (56 kB)
Collecting jinja2==2.10.1
  Downloading Jinja2-2.10.1-py2.py3-none-any.whl (124 kB)
Collecting kombu==4.2.1
  Downloading kombu-4.2.1-py2.py3-none-any.whl (177 kB)
Collecting markupsafe==1.0
  Downloading MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zhzrprbs/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zhzrprbs/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zhzrprbs/markupsafe/pip-egg-info
         cwd: /tmp/pip-install-zhzrprbs/markupsafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zhzrprbs/markupsafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
remote: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
remote:
To <serverip>:wharf
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@<serverip>:wharf'
```

**Comment by palfrey** [comment]
Looks like an [upstream issue] (https://github.com/pallets/markupsafe/issues/57) with markupsafe. I'll have a look at this tomorrow

**Comment by palfrey** [comment]
Yup, all fixed now
