### ISSUE TITLE
Internal Server Error when inspecting an app

### ISSUE THREAD

**Issue by bstst** [palfrey/wharf#83]
Logs show this:

```
2020-04-03T10:49:14.693543676Z app[web.1]: Internal Server Error: /apps/wharf
2020-04-03T10:49:14.693586990Z app[web.1]: Traceback (most recent call last):
2020-04-03T10:49:14.693593638Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-04-03T10:49:14.693598464Z app[web.1]:     response = get_response(request)
2020-04-03T10:49:14.693602635Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-04-03T10:49:14.693607170Z app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-04-03T10:49:14.693611397Z app[web.1]:   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-04-03T10:49:14.693615797Z app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-04-03T10:49:14.693619949Z app[web.1]:   File "/app/apps/views.py", line 304, in app_info
2020-04-03T10:49:14.693624000Z app[web.1]:     'postgres': postgres_list(app_name),
2020-04-03T10:49:14.693628007Z app[web.1]:   File "/app/apps/views.py", line 221, in postgres_list
2020-04-03T10:49:14.693654202Z app[web.1]:     return db_list(app_name, data)
2020-04-03T10:49:14.693661382Z app[web.1]:   File "/app/apps/views.py", line 216, in db_list
2020-04-03T10:49:14.693665327Z app[web.1]:     return generic_list(app_name, data, "NAME", ["NAME", "VERSION", "STATUS", "EXPOSED PORTS", "LINKS"])
2020-04-03T10:49:14.693669990Z app[web.1]:   File "/app/apps/views.py", line 192, in generic_list
2020-04-03T10:49:14.693674047Z app[web.1]:     raise Exception("Can't find '%s' in '%s'" % (f, lines[0].strip()))
2020-04-03T10:49:14.693677785Z app[web.1]: Exception: Can't find 'NAME' in '=====> Postgres services'
2020-04-03T10:49:14.694902522Z app[web.1]: "GET /apps/wharf HTTP/1.1" 500 145
```

**Comment by palfrey** [comment]
Guessing you're running the Postgres plugin with version >1.9.5? In which case this is #75. Downgrade the Postgres plugin, and it should work again. The version requirement is mentioned on the README (see https://github.com/palfrey/wharf#setup).

**Comment by bstst** [comment]
Indeed, apologies.
